Clarify course instance cloning instructions
apluslms/a-plus pull request #1059
Opened 2022-08-16 13:59 UTC by ihalaij1

# Description

**What?**

Clarify the instructions related to course instance cloning based on teacher feedback.

**Why?**

Teacher gave good feedback.

**How?**

See the changes to the code.

Fixes #1055

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested that the new info notifications appear.

**Did you test the changes in**

- [x] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [x] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2022-08-16 13:59 UTC, ihalaij1 commented
Note that this PR automatically removed some unused translations.

2022-08-16 14:09 UTC, ihalaij1 commented
I did not change the year/semester instructions yet, because we need to first choose what we want to do.
Do we want to remove the year & semester fields, and use the unique URL key as a part of the Git manager key, or do we just change the instructions to be less technical?

If we use the URL keys in Git manager keys, then the Git manager keys will be more random and not as uniform. Currently, the keys for all new courses are in the form of ``COURSE-KEY_YYYYSemester``, but if we use the URL key instead, they will become more random, such as ``COURSE-KEY_2022s``, ``COURSE-KEY_fall2022``, ``COURSE-KEY_2022``.

What do we want?

2022-08-16 14:58 UTC, PasiSa commented
> Also, I don't know how we want to explain what the Sisu dropdown selector does, is it mandatory, and how to tell teachers, which one of the cryptic options to choose. If you have suggestions, I will make the changes.

This data comes directly from Sisu: starttime - endtime (type). For each course, Sisu has multiple realizations from near past and near future, and typically the type seems to be "teaching-participation-lectures" for the actual course and "exam-exam" for the exams, but I'm not sure if other values are also possible on some courses. Especially for exams there seems to be multiple entries, because there are multiple exam opportunities during a year. I don't have other ideas at the moment, but to maybe add better description to the description text under the menu to explain how to read the options. The selector is mandatory to get the correct list of students enrolled, because different instances have different students.

2022-08-16 18:02 UTC, Mankro commented
> I did not change the year/semester instructions yet, because we need to first choose what we want to do. Do we want to remove the year & semester fields, and use the unique URL key as a part of the Git manager key, or do we just change the instructions to be less technical?
> 
> If we use the URL keys in Git manager keys, then the Git manager keys will be more random and not as uniform. Currently, the keys for all new courses are in the form of `COURSE-KEY_YYYYSemester`, but if we use the URL key instead, they will become more random, such as `COURSE-KEY_2022s`, `COURSE-KEY_fall2022`, `COURSE-KEY_2022`.
> 
> What do we want?

I think we could keep the current naming scheme `COURSE-CODE_YYYYSemester` and then we wouldn't remove the form fields for the year and semester. There is some value in keeping the internal gitmanager course keys more structured and organized. (Though, if the teacher can still actually change the course key in the Edit course - Git manager tab, then they can still override the keys with nonsense.)

Even though one teacher didn't like entering extra info like the year and semester, I still think it is not too much to ask. The teacher should know on which year and semester they are running their courses.

2022-08-16 18:03 UTC, Mankro commented
Upstream master has changed after your other PR was merged (#1058). You may rebase and fix django.po translations.

2022-08-17 08:56 UTC, PasiSa commented
> > Also, I don't know how we want to explain what the Sisu dropdown selector does, is it mandatory, and how to tell teachers, which one of the cryptic options to choose. If you have suggestions, I will make the changes.
> 
> This data comes directly from Sisu: starttime - endtime (type). For each course, Sisu has multiple realizations from near past and near future, and typically the type seems to be "teaching-participation-lectures" for the actual course and "exam-exam" for the exams, but I'm not sure if other values are also possible on some courses. Especially for exams there seems to be multiple entries, because there are multiple exam opportunities during a year. I don't have other ideas at the moment, but to maybe add better description to the description text under the menu to explain how to read the options. The selector is mandatory to get the correct list of students enrolled, because different instances have different students.

How about the following description text to explain the dropdown menu?
"Course instance from which students are enrolled. It shows the start and ending times of the course instance, along with the enrollment type (e.g. course participations or exam enrollment)"

The problem is that this menu is built by the organization-specific SIS plugin. If some other university started using this feature, they might have completely different format in menu entries.

2022-08-17 10:28 UTC, Mankro commented
> How about the following description text to explain the dropdown menu? "Course instance from which students are enrolled. It shows the start and ending times of the course instance, along with the enrollment type (e.g. course participation or exam enrollment)"
> 
> The problem is that this menu is built by the organization-specific SIS plugin. If some other university started using this feature, they might have completely different format in menu entries.

This sounds good to me! Let's return to the "other universities" later in the future if this becomes a problem.

2022-08-17 12:46 UTC, ihalaij1 commented
I made all the changes now, this is ready for a review.

2022-08-17 18:04 UTC, Mankro requested changes
Great! I thought of a few small changes.

2022-08-17 18:04 UTC, Mankro commented on locale/en/LC_MESSAGES/django.po
> +"course participation or exam enrollment). The below option only applies if "
```suggestion
"ending times of the course instance, along with the enrolment type (e.g., "
"course participation or exam enrolment). The option below only applies if "
```
We have used the spelling "enrolment" in the UI.

2022-08-18 10:43 UTC, ihalaij1 commented
These changes have been implemented now!

2022-08-18 17:54 UTC, Mankro approved these changes
Excellent! I will merge this now.

2022-08-18 17:55 UTC, merged