Submitters aren't lost when saving deviations
apluslms/a-plus pull request #1066
Opened 2022-08-25 13:21 UTC by EerikSaksi

The list of submitters are cached in localStorage whenever the
save button is clicked. On page load, the localStorage is loaded,
and the list of submitters are added to the form.

Fixes #998

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

I tested different situations, such as refreshing the page, making sure a selected submitter was present after a save, and that no submitter was present after a page. I also made sure that users could still be deleted and wouldn't appear after a save.

**Did you test the changes in**

- [ ] Chrome
- [X] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [X] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [X] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [X] Other documentation (mention below which documentation).
I added comments as this was quite a small change
# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2022-09-06 11:14 UTC, ihalaij1 requested changes

2022-09-12 06:16 UTC, ihalaij1 approved these changes
Nice!

2022-10-28 12:55 UTC, Mankro requested changes
Thanks! I don't really like this hackish JavaScript solution. It should be possible to implement this in the backend that validates the forms. The JavaScript solution attached to the deadline deviation form page does not extend to other forms that have the same issue with `UsersSearchSelectField`. Additionally, this solution breaks the click event handlers in the buttons representing the selected users.

The commit message could be made a bit clearer. It mentions "saving deviations", but the problem is specific to not passing the validation (required field missing), not just saving generally.

I wrote down ideas about the backend solution in the issue:
https://github.com/apluslms/a-plus/issues/998#issuecomment-1294953902

2022-10-28 17:06 UTC, closed without merging

2022-10-28 17:13 UTC, Mankro commented
I tried to modify the `clean()` method of class `SearchSelectField` so that it updates the custom `initial_queryset` attribute. It worked so well that I have already finished the issue. Since this pull request tried to use a different approach via JavaScript and it wasn't optimal, I closed this pull request. It will not be merged.

https://github.com/apluslms/a-plus/commit/b16e75e300bb36b2323297770375c88e309cba24