Metadata values added to the modal in the submission inspection
apluslms/a-plus pull request #1070
Opened 2022-09-02 08:26 UTC by EerikSaksi

# Description

When inspecting a submission and opening the submission details modal, this modal did not have the meta_data field of the Submission model.

**Why?**
This can help admins and teachers debug issues

**How?**

In the modal template, we iterate over the key value pairs of the meta_data dictionary and display the keys and values.

Fixes #614 

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [X] Manual testing.

Made sure that the correct metadata values were displayed for the corresponding labels, ensured that the fallback (No values to display) works when the metadata is empty.

**Did you test the changes in**

- [ ] Chrome
- [X] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Programming style
- [X] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-09-06 08:38 UTC, ihalaij1 requested changes
The commit message should also include ``Fixes #614``.

2022-09-06 10:51 UTC, EerikSaksi commented
Added Fixes #614

2022-09-06 11:12 UTC, ihalaij1 requested changes

2022-09-12 06:14 UTC, ihalaij1 approved these changes

2022-09-20 10:27 UTC, PasiSa commented
> Added Fixes #614

I can't see this in commit message, at least through GitHub interface?

2022-10-31 20:41 UTC, Mankro requested changes
Nice! You just forgot the `<dl>` html element from the description list. I will add it myself and merge this now.

2022-10-31 20:48 UTC, Mankro approved these changes

2022-10-31 20:49 UTC, merged