Added tooltips to show model solutions buttons
apluslms/a-plus pull request #1079
Opened 2022-09-13 08:22 UTC by EerikSaksi

Added a bootstrap tooltip to the "Show model solutions" button. The tooltips are only shown once to the user through the use of localStorage. This is to prevent the tooltips from becoming annoying, and there is no reason to draw attention to the tooltips more than once.

Fixes #856

# Description

**What?**

The first time the client comes across a "show model solutions" button, this button has a tooltip bringing the users attention to it.

**Why?**

There were reports that users didn't notice the model solutions button. By adding the tooltip users should notice this button better. By only showing this button once we also avoid this from becoming annoying and distracting.

**How?**

We first check if the user has seen the model solutions tooltips before. This can be checked from the user's localStorage, based on the value of model-solutions-tooltip-shown. If this isn't true, we register an event listener for all ajax requests to finish. This means that all exercises have loaded. We then check if any of these exercises have the "Show model solutions" button in them. If this is the case, we enable the tooltips on these buttons, and set the value of model-solutions-tooltip-shown to true. 

Fixes #856 

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [X] Manual testing.

I tested multiple cases. The 6.3 module has multiple model solutions buttons, so I ensured that these have tooltips on first load. After a refresh, I ensured that no tooltips were visible, and that the localStorage had model-solutions-tooltip-shown set to true. I also ensured that model-solutions-tooltip-shown was not set to true in module 6.1, which has no "Show model solutions" buttons.

**Did you test the changes in**

- [ ] Chrome
- [X] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [X] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-10-04 08:00 UTC, ihalaij1 requested changes
Nice!

The whole file ``exercise.html`` should be updated to use tabs instead of spaces for indentation (in a separate commit from your other changes).

Also, ``const`` and ``let`` should be used with variables instead of ``var`` when ``var`` is not required.

Could you add the missing semicolons at the end of the statements (like in the script above), so that the coding style is consistent?

2022-10-04 14:23 UTC, ihalaij1 approved these changes
Nice!

2022-11-11 15:36 UTC, Mankro requested changes
I am doubtful if these tooltips are really a good way to improve the visibility of the exercise frame buttons. They feel a bit clunky and they are only shown once, thus they won't help if the user forgets about it later on and doesn't easily spot the buttons. 

I would like to reconsider if changing the size and other visuals of the buttons could solve the issue (#856).

What do you think? Note the comments below too.

2022-11-11 15:36 UTC, Mankro commented on exercise/templates/exercise/exercise.html
> +				modelButtons.tooltip('show');
I got these errors, which suggest that the `ajaxStop` event might not be very reliable for detecting if the document as well as all the exercises have really loaded. If Bootstrap isn't ready yet early in the page load, I guess tooltips can not work.

I was testing on the Programming 1 (O1) course.

```
Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'show'
    jQuery 5
    <anonymous> http://localhost:8000/def/current/w10/ch03/#chapter-exercise-3:143
    jQuery 7
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
jquery-3.6.0.min.js:2:2616
    jQuery 5
    <anonymous> http://localhost:8000/def/current/w10/ch03/#chapter-exercise-3:143
    jQuery 7
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875
    jQuery 2
    loadName http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:872
    nextExercise http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:73
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:327
    jQuery 6
    load http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:305
    $.fn[loadName]/< http://localhost:8000/static/exercise/chapter.js?ad188cecaa814874a5cd4bd9140ef6e195399d61:875


Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'show'
    jQuery 5
    <anonymous> http://localhost:8000/def/current/w10/ch03/#chapter-exercise-3:143
    jQuery 8
    submit http://localhost:8080/static/default/_static/pheromones.js:339
    add http://localhost:8080/static/default/_static/pheromones.js:188
    addLocation http://localhost:8080/static/default/_static/pheromones.js:294
    scrollTimer http://localhost:8080/static/default/_static/pheromones.js:171
    setTimeout handler*onScroll http://localhost:8080/static/default/_static/pheromones.js:168
    bindScroll http://localhost:8080/static/default/_static/pheromones.js:180
    init http://localhost:8080/static/default/_static/pheromones.js:76
    <anonymous> http://localhost:8080/static/default/_static/pheromones.js:502
    jQuery 10
jquery-3.6.0.min.js:2:2616
```

2022-11-11 15:36 UTC, Mankro commented on exercise/templates/exercise/exercise.html
> +		//when ajaxStop event fires, we have received all exercises, so enable their tooltips.
```suggestion
		// When the ajaxStop event fires, we have received all exercises, so enable their tooltips.
```

2022-11-11 15:36 UTC, Mankro commented on exercise/templates/exercise/exercise.html
> +				//remember that client has seen the tooltips so they dont see them again
```suggestion
				// Remember that the client has seen the tooltips so they don't see them again.
```

2022-11-11 15:36 UTC, Mankro commented on exercise/templates/exercise/exercise.html
> +		})
```suggestion
		});
```

2022-11-14 11:00 UTC, EerikSaksi commented
I can just implement the larger buttons as was originally suggested. I tried to do this initially but found it was hard to do this without it looking like bad design.

2022-11-21 11:21 UTC, Mankro commented
> I can just implement the larger buttons as was originally suggested. I tried to do this initially but found it was hard to do this without it looking like bad design.

Yes, let's try that again. The Sass/CSS styles must be modified too so that the exercise frame navbar looks clean overall. There are other buttons in the navbar besides the model solution button. All those buttons could use the same styles.

One idea for experimenting could be to set the buttons' height to 100% of the navbar, or 50% and stack two buttons vertically.

2022-11-23 10:24 UTC, EerikSaksi commented
The obvious solution would be to just change the buttons from aplus-button--xs to aplus-button--md. They become more visible, but if there are 3 buttons, then the third one overflows to the next row (on a 1080p monitor with 100% zoom, other resolutions and zooms could also be considered)

### Current button sizes
![three_xs](https://user-images.githubusercontent.com/46625399/203523024-4a3118ab-30f5-40bf-b99e-5f28f2cd125b.png)

### md buttons with two buttons 
![two_md](https://user-images.githubusercontent.com/46625399/203523173-b4b03742-ff6a-49fd-ba1d-5c0fb33e6cb5.png)

### md buttons with three buttons (one overflows to new row)
![three_md](https://user-images.githubusercontent.com/46625399/203523370-6a06d401-1ec1-4951-8042-5b2de7f13866.png)

2022-11-23 10:52 UTC, Mankro commented
The last screenshot ("md buttons with three buttons (one overflows to new row)") looks good to me! Are you happy with it yourself? Does the layout remain clean on smaller screens too?

2022-11-23 11:59 UTC, EerikSaksi commented
On smaller screens the 3 buttons seem to go on their own row which looks good

2022-11-24 13:43 UTC, Mankro approved these changes
Great, this works well! I slightly clarified the commit message, force-pushed and now I will merge this pull request.

2022-11-24 13:44 UTC, merged