Added enrollment question check to CourseModulePermissionBase
apluslms/a-plus pull request #1080
Opened 2022-09-14 10:34 UTC by EerikSaksi

Before, the permission check would work by simply checking whether the module had opened yet. With this check, the module opening time is only checked if the exercise is not an enrollment question

Fixes #679

# Description

**What?**

This change adds a check for if the exercise is an enrolment question to CourseModulePermissionBase.

**Why?**

Enrolment questions should be accessible before the module is open

**How?**

Before the check for if the module is open, we check whether the exercise is an enrolment question. If this is the case, then we do not care if the module is open.

Fixes #679 

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [X] Manual testing.

Ensuring that students can open the URL to enrolment exercises in modules which have not opened yet, making sure that no error is thrown when the view supplied to CourseModulePermissionBase does not have a exercise attribute (when called from ModuleView and not ExerciseView)

**Did you test the changes in**

- [ ] Chrome
- [X] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-09-20 10:49 UTC, PasiSa requested changes
One style-related proposal, otherwise looks good to me. Didn't test this PR (or my proposal), though.

2022-09-20 10:49 UTC, PasiSa commented on course/permissions.py
> +        if not (hasattr(view, 'exercise') and view.exercise.status in ('enrollment', 'enrollment_ext')) and not module.is_after_open():
Should we rather use
```
view.exercise.status in (LearningObject.STATUS.ENROLLMENT, LearningObject.STATUS.ENROLLMENT_EXTERNAL)
```
Perhaps could also be split into multiple lines, as this line is getting rather long

2022-09-20 11:03 UTC, EerikSaksi commented
Changed the formatting and added LearningObject import @PasiSa

2022-09-20 11:36 UTC, PasiSa approved these changes

2022-09-21 16:47 UTC, Mankro requested changes
Good start! When I tested this, I noticed that it really does not work yet because there is also another permission (`ExerciseVisiblePermissionBase`) that checks the module opening time. Fixing that other permission is easy. I also thought that some details could be formatted better. `CourseModulePermissionBase.has_object_permission()` has the part `module.requirements.exists()` in the end that should not be used in enrollment questionnaires.

I made some changes myself and pushed them to git so that you may finalize this PR.

**git commit message**
* commit message heading: use the imperative mood
* line length: at most 80 characters
* the heading could be reworded better. Emphasize the goal ("enrollment questionnaires should not be affected by the module opening time") instead of the implementation details on the code lines ("check in CourseModulePermissionBase").

2022-09-22 07:22 UTC, EerikSaksi commented
Thanks @Mankro for the feedback, I will get to it!

2022-09-23 13:52 UTC, EerikSaksi commented
I tested the new changes, it seems like the enrolment questionnaire is accessible before the course is open, but the course is not. I am not sure if this is the desired behaviour.

https://user-images.githubusercontent.com/46625399/191976229-87631e78-d401-4e5f-bb4a-ef38aaccd975.mp4

2022-09-30 07:00 UTC, Mankro commented
> > it seems like the enrolment questionnaire is accessible before the course is open, but the course is not. I am not sure if this is the desired behaviour.
> 
> I haven’t studied this issue / PR properly at all, but I’ll just mention that AFAIC, it shouldn’t be possible to fill in or even see the enrollment questionnaire before the course is actually open.

If I remember correctly, the enrollment questionnaire is supposed to be open if the course settings (enrollment starting time and enrollment ending time) define so. If the teacher wants to set enrollment starting time before the course opening time, then it is possible.

If the enrollment opening times are not defined, they default to the course opening times.

If the enrollments are fetched from Sisu, we should check what happens. Is access restricted by the course opening times?

2022-09-30 08:44 UTC, EerikSaksi commented
I added a test for accessing the enrollment exercise which tests combinations of starting times and enrollment starting times which passes. I might have misunderstood what the expected behavior is but if the test describes the expected behavior then this should work.

2022-10-17 19:41 UTC, Mankro approved these changes
Good job with the unit tests! I added some more tests, rebased and now I am merging this.

2022-10-17 19:42 UTC, merged