Separate unconfirmed points in all results data
apluslms/a-plus pull request #1195
Opened 2023-06-08 14:47 UTC by lainets

# Description

**What?**

Add checkbox to the all results UI to include/exclude unconfirmed points and backend logic for it.

**Why?**

#941

**How?**

Add a filter to the submission query to filter out unconfirmed submissions.

Closes #941

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [X] Django unit tests.
- [X] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [X] Manual testing.

Made unconfirmed submissions and checked that the filter leaves them out.

**Did you test the changes in**

- [X] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [X] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [X] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [X] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2023-06-08 14:54 UTC, lainets commented
This doesn't handle unconfirmed points for exercises that are direct children of a module instead of a learning object. I figure this is required, and will be adding it tomorrow.

2023-06-09 14:20 UTC, lainets commented
This should only be merged after https://github.com/apluslms/a-plus/pull/1194.

Also, I wonder if fetching all submissions from the server and doing the computations on the client would be prohibitively slow or take too much RAM. It seems like that would be much simpler than the current solution. (also stops the need to reload and remake the results table from scratch)

2023-08-22 21:21 UTC, Mankro requested changes
Great work! A couple of very minor details should be cleaned up. I am not very familiar with the OuterRef query sets so I don't completely understand the new database query for the confirmed submissions. I will trust you with that. Hopefully, the new queries with the added complexity don't perform too slowly in the large courses.

2023-08-22 21:21 UTC, Mankro commented on exercise/api/csv/views.py
> +                    course_module__course_instance = self.instance,
Inconsistent whitespace around `=`

2023-08-22 21:27 UTC, Mankro commented on exercise/templates/exercise/staff/results.html
> +						{% translate "RESULTS_SHOW_UNCONFIRMED_POINTS" %}
About the `checked` attribute, I suppose the default value for loading the points data is really set in the JavaScript. So the visible "checked" state of the checkboxes must match the behavior of the JavaScript code. The JS does not automatically load unofficial points when the page is opened, right?

2023-08-25 13:01 UTC, lainets commented on exercise/templates/exercise/staff/results.html
> +						{% translate "RESULTS_SHOW_UNCONFIRMED_POINTS" %}
I changed the values to `unofficial` and `unconfirmed`, and set them to be unchecked initially. I also refactored the load function to load the variables from the DOM, so the event listeners don't have to.

2023-08-25 17:22 UTC, Mankro approved these changes
Thanks!

2023-08-25 17:22 UTC, Mankro commented on exercise/static/exercise/results_staff.js
> +            show_unconfirmed = $('input.unconfirmed-checkbox').prop('checked')
Semicolons at the end of the lines.

2023-08-25 17:22 UTC, merged