Documentation on LTI 1.3 platform configuration
apluslms/a-plus pull request #1205
Opened 2023-06-20 12:50 UTC by PasiSa

# Description

**What?**

[ANSWER HERE]

**Why?**

[ANSWER HERE]

**How?**

[ANSWER HERE]

Fixes #<issue number>

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [ ] Manual testing.

[ADD A DESCRIPTION ABOUT WHAT YOU TESTED MANUALLY]

**Did you test the changes in**

- [ ] Chrome
- [ ] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-06-27 17:32 UTC, Mankro requested changes
Great, this explains a lot! Would you fix the typos before merging?

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +LTI's line items through the LTI API. Of the other commonly user features, the LTI 1.3
```suggestion
LTI's line items through the LTI API. Of the other commonly used features, the LTI 1.3
```
typo

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  starts the authentication handshake with tool, as specified in [Section
```suggestion
  starts the authentication handshake with the tool, as specified in [Section
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +* **JWKS URL** is the address from which the tool's public key can found in
```suggestion
* **JWKS URL** is the address from which the tool's public key can be found in
```
typo

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  user's real name, E-mail and student ID with the tool.
```suggestion
  the user's real name, E-mail and student ID with the tool.
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +* **Issuer (or platform ID)**: This the issuer identifier, used in JWT tokens in
```suggestion
* **Issuer (or platform ID)**: This is the issuer identifier, used in JWT tokens in
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  response to the login initiation message, as specified in [Section
The sentence is missing something. 

Is this correct?
... the address TO WHICH the tool sends its response ...

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  in different LTI messages, for example when for updating the scores from tool.
```suggestion
  in different LTI messages, for example for updating the scores from the tool.
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +In addition the client ID (and often also the deployment ID) need to be
```suggestion
In addition, the client ID (and often also the deployment ID) need to be
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +setting in admin view.
```suggestion
To include a service or exercise from the LTI Tool as an A+ exercise, the "lti1p3" directive
can be used in the course RST source, together with the label identifying the
LTI tool. This label must be equal to what was configured in the "Menu label"
setting in the A+ admin view.
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +what tool requires. More information and an example of the configuration is
```suggestion
what the tool requires. More information and an example of the configuration is
```

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +similarly to other external services.
Could this be rephrased better?

2023-06-27 17:32 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +by using the LTI_TOKEN_LIFETIME settings variable. This defaults to 3600 seconds
```suggestion
by using the `LTI_TOKEN_LIFETIME` settings variable. This defaults to 3600 seconds
```

2023-06-28 10:49 UTC, PasiSa commented
Thanks for the comments, they are now address, I believe.

2023-06-28 11:42 UTC, Mankro requested changes
I am afraid you missed two of the previous comments.

2023-06-28 11:42 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  response to the login initiation message, as specified in [Section
You didn't react to this yet.

2023-06-28 11:42 UTC, Mankro commented on doc/LTI_1.3_PLATFORM.md
> +  in different LTI messages, for example when for updating the scores from tool.
You didn't react to this yet.

2023-06-28 11:43 UTC, Mankro commented
Since Github collapses comments in the middle when there are many of those, you need to detect and click the "show" button to see the missing comments.

2023-06-28 12:24 UTC, PasiSa commented
Ok, maybe now?

2023-06-28 13:26 UTC, Mankro approved these changes
Excellent!

2023-06-28 13:27 UTC, merged