Show pseudonymized names
apluslms/a-plus pull request #1211
Opened 2023-06-28 08:40 UTC by Mikael-Lenander

This turned out to be very difficult. The only way I came up with is to modify the user instance's fields without storing the changes to the database. I don't know if this is the cleanest way to do it but the upside is that is doesn't require changing the API of user of userprofile. I couldn't figure out a way to pseudonymize the 'All results' page since it doesn't fetch the user data in the view but through a JavaScript script so I can't access the request.session object which contains a boolean value 'pseudonymize' that determines whether personal data should be pseudonymized. Also, the forms are difficult to pseudonymize without changing the form field values which sounds dangerous.

2024-04-02 11:31 UTC, murhum1 commented on exercise/staff_views.py
> +            print(submission.submitters)
Should remove debug print

2024-04-04 06:42 UTC, murhum1 requested changes
Just wrote up comments earlier and didn't actually submit them, sorry! New to this review business. Anyway, comments up now.

2024-04-04 10:17 UTC, mikaelGusse commented on userprofile/pseudonymize.py
Added a seed such that all the fields that are generated are consistent per user now

2024-04-04 10:18 UTC, mikaelGusse commented on external_services/templatetags/external_services.py
> +
Fixed

2024-04-04 10:18 UTC, mikaelGusse commented on exercise/templates/exercise/staff/_assessment_panel.html
> +					{% blocktranslate trimmed with user="Somebody" time=submission.grading_time %}
Done

2024-04-04 10:25 UTC, mikaelGusse commented on exercise/templates/exercise/_submission_info.html
> +				Somebody
Done

2024-04-04 10:28 UTC, mikaelGusse commented
> Just wrote up comments earlier and didn't actually submit them, sorry! New to this review business. Anyway, comments up now.

Thanks for the comments! Just went through them, do you think the seed system there is ok for keeping the pseudonymizations consistent?

2024-04-04 11:41 UTC, murhum1 approved these changes
Thanks! Looks fine now.

2024-04-04 11:42 UTC, merged