Add highlighting to model solution feedback texts
apluslms/a-plus pull request #1212
Opened 2023-06-29 14:32 UTC by Mikael-Lenander

# Description

**What?**

Some model submission questionnaires have feedback texts. Some of these are shown also when viewing the model solution of the questionnaire. Highlights these feedback texts.

**Why?**

In some courses (O1 especially), the feedback texts contain useful information. Without highlighting, the texts are easily neglected, when reading the model answer.

**How?**

Adds css class that highlights text.

Fixes #1118

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [ ] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

The highlighting only affects the style of the model solution view, not the actual questionnaire.

**Did you test the changes in**

- [ ] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-08-16 10:42 UTC, ihalaij1 approved these changes
Looks good! Can you change the commit message to include Fixes #1118?

2023-08-22 08:50 UTC, Mikael-Lenander commented
Also highlight hints while doing the exercise, not just model solution hints.

2023-08-26 20:30 UTC, Mankro requested changes
Good! Make the minor changes described below and rebase the git branch onto the upstream master. Then, we can merge.

2023-08-26 20:33 UTC, Mankro commented on assets/sass/protocols/_quiz1.scss
> +	background-color: #ffefaa;
In Firefox, you can install the WAVE extension to easily check if the colors pass the accessibility standards.

https://addons.mozilla.org/en-US/firefox/addon/wave-accessibility-tool/

2023-08-26 20:50 UTC, Mankro commented on assets/sass/protocols/_quiz1.scss
> +.question-hint {
MOOC-Grader change in its master branch:
https://github.com/apluslms/mooc-grader/commit/c697bee96202999725bd08ce0b596012a1a2e674

2023-08-28 13:29 UTC, Mankro approved these changes
Great! I fixed the git conflict myself and I will merge this now.

2023-08-28 13:29 UTC, merged