Display personal deadline extensions on a student’s points page
apluslms/a-plus pull request #1216
Opened 2023-07-18 14:12 UTC by Mikael-Lenander

# Description

**What?**

Displays deadline extensions in the points page with a tag in the module heading and a clock icon next to each exercise.

**Why?**

Students and staff members see deadline extensions more easily.

**How?**

Adds two custom template tags that check if an exercise/module has a personal deadline.

Fixes #1119

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [x] Django unit tests.
- [] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

The deadline deviations are only shown on the points page when the module is open and the student has time left to submit the exercise. Works for both module are exercise deviations. Both students and staff members see the deviations.

**Did you test the changes in**

- [x] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [x] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [ ] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [ ] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

Template blocks are not indented.

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

2023-08-16 09:28 UTC, ihalaij1 requested changes
Great, I have just one question.

Is using ``deepcopy`` really necessary? Does the code not work without it?

Also, the commit message should include Fixes #1119 on separate line, with an additional empty line above it.

2023-08-16 11:10 UTC, Mikael-Lenander commented
Without deepcopy, the iterator returned by entry['flatted'] is exhausted. When this iterator is looped over again to display the entries in the results page, nothing shows up:
![image](https://github.com/apluslms/a-plus/assets/65553595/e7fde88c-59cb-40c6-b05b-6a6e516f9c3e)
The only solution I came up with was to copy the iterator.

2023-08-16 11:18 UTC, ihalaij1 approved these changes
Ready for merge!

2023-08-27 14:57 UTC, Mankro approved these changes
Nice! I will make minor changes myself to improve accessibility and then merge this.

2023-08-27 15:00 UTC, merged