Add option to exercises that reveal model solution after deadline or …
apluslms/a-plus pull request #1220
Opened 2023-08-09 10:36 UTC by Mikael-Lenander

…full points

# Description

**What?**

Adds the possibility to configure an exercise so that the model solution is shown after a student gets full points or after the deadline/personal extensions have passed.

**Why?**

O1 (and other courses) need.

**How?**

Adds a new option to RevealRule model.

Fixes #1145

# Testing

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [x] Django unit tests.
- [ ] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

With this option, model solution is shown after deadline or with full points, but not with all submissions used. Deadline options still works after refactoring.

**Did you test the changes in**

- [x] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

# Translation

- [x] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [x] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-08-15 13:27 UTC, ihalaij1 requested changes
Excellent!

I tested this and it seems to work great!
See below for some minor changes.

Also, the commit message should be shorter and include ``Fixes #1145`` on separate line, with an additional empty line above it.

2023-08-15 13:27 UTC, ihalaij1 commented on exercise/reveal_models.py
>              RevealRule.TRIGGER.DEADLINE_ALL
Could you add a comma at the end of this list? :)

2023-08-15 13:27 UTC, ihalaij1 commented on exercise/reveal_models.py
> +                return True
You can shorten this to ``return self._is_revealed_due_to_time(state, time)``

2023-08-15 13:27 UTC, ihalaij1 commented on exercise/reveal_models.py
> +                return True
You can shorten this to ``return self._is_revealed_due_to_full_points(state)``

2023-08-15 13:27 UTC, ihalaij1 commented on exercise/reveal_models.py
>                      return True
Could you create a helper function ``_is_revealed_due_to_max_submissions`` for this as well?

2023-08-15 13:27 UTC, ihalaij1 commented on exercise/reveal_models.py
> +                return True
You can shorten this to ``return self._is_revealed_due_to_full_points(state) or self._is_revealed_due_to_time(state, time)``

2023-08-16 08:12 UTC, Mikael-Lenander commented
Added a delay field to the reveal rule form with the DEADLINE_OR_FULL_POINTS trigger selected.

2023-08-16 08:51 UTC, ihalaij1 approved these changes
Looks good!

2023-08-16 10:48 UTC, ihalaij1 requested changes
There's a linter error that should be fixed still.
```
exercise/reveal_models.py
  Line: 49
    pylint: no-else-return / Unnecessary "elif" after "return", remove the leading "el" from "elif"
```

2023-08-16 11:28 UTC, Mikael-Lenander commented
Done

2023-08-16 11:44 UTC, ihalaij1 approved these changes
Ready for merge!

2023-08-23 11:05 UTC, Mikael-Lenander commented
Still added support to configure this options from files coming from gitmanager

2023-08-28 08:13 UTC, Mankro approved these changes
At a quick glance, this looks very nice and clean! @lainets promised to take a closer look and merge this after that.

2023-08-28 08:13 UTC, Mankro commented on exercise/reveal_models.py
> +    def _is_revealed_due_to_time(self, state: 'BaseRevealState', time: datetime.datetime) -> bool:
The type hint for `time` is wrong. Since it can be `None`, the type is `Optional[datetime.datetime]`

2023-08-28 08:13 UTC, Mankro commented on exercise/reveal_models.py
> +    def _is_revealed_due_to_max_submissions(self, state):
Type hints were not added here for the parameters.

2023-08-28 09:05 UTC, lainets commented
The changes are missing tests and https://github.com/apluslms/a-plus/blob/0d5be74b55ddb352260b39f7b64fc448befa85c2/exercise/viewbase.py#L72 don't include the new option. I'll fix these myself to get this merged quickly.

2023-08-28 09:34 UTC, merged