Set chapter as module model answer
apluslms/a-plus pull request #1229
Opened 2023-08-18 11:31 UTC by Mikael-Lenander

# Description

**What?**

Modules can be configured a chapter as model answer.  The chapters visibility is controlled through a RevealRule.

**Why?**

Chapters may include prujus to previous modules, especially in O1.

**How?**

Adds model answer and reveal rule fields to CourseModule. A Chapter can check (by reversing the relation) if it is a model solution to a module. Any LearningObject can check if it is a child of this kind of Chapter. Adds a key 'is_revealed' to every LearningObject entry in cache. Updates exercise permission class to check LearningObject's visibility. Adds new reveal state that takes all module's exercises into account.

Fixes #1098

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [x] Django unit tests.
- [x] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Made chapter 2.0 module 1's model answer. Added deadline deviation to module 1 for student so that module 1 and 2 are open simultaneously. Made sure chapter 2.0 is not visible to student, not through toc, results or direct link.

**Did you test the changes in**

- [x] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [x] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?
- [x] Did you use Python type hinting in all functions that you added or edited? ([type hints](https://docs.python.org/3/library/typing.html) for function parameters and return values)

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2023-08-23 11:55 UTC, ihalaij1 requested changes
Great!
I had just a few comments, it seems to be working.
Nice that you added tests as well!
You should still fix the linter errors, though.

2023-08-23 11:55 UTC, ihalaij1 commented on exercise/permissions.py
> +                return False
The code in this if-statement is indented twice.

2023-08-23 11:55 UTC, ihalaij1 commented on exercise/reveal_states.py
> +            cached_module,_,_,_ = cached_points.find(module)
Could you add spaces after the commas?

2023-08-23 11:55 UTC, ihalaij1 commented on exercise/tests_cache.py
> +        chapter_entry,_,_,_ = p.find(module_chapter)
Could you add spaces after the commas?

2023-08-27 21:02 UTC, Mankro requested changes
You have done great work! There is very little time left now to finish this before the version release. Please, at least fix the trivial parts that I have commented. Bigger performance optimizations could be done in the future if necessary. 

In addition, rebase onto the upstream and squash your commits. I can then merge this.

2023-08-29 10:20 UTC, Mikael-Lenander commented on exercise/reveal_states.py
> +        return sum([min(exercise['submission_count'], _get_max_submissions(exercise)) for exercise in self.exercises])
Generally, if for some reason the submission count is greater than max submission count, we want to use the max submission count.

2023-08-29 10:46 UTC, Mikael-Lenander commented
Still fixed linting errors.

2023-08-29 13:26 UTC, Mankro commented on exercise/reveal_states.py
> +        return sum([min(exercise['submission_count'], _get_max_submissions(exercise)) for exercise in self.exercises])
OK! :+1:

2023-08-29 13:38 UTC, Mankro approved these changes
Thanks, I will merge this now.

2023-08-29 14:33 UTC, merged