Exclude WAITING submissions from all results table
apluslms/a-plus pull request #948
Opened 2022-01-10 12:33 UTC by skulonen

# Description

**What?**

This PR changes the all results table to ignore submissions in the states `WAITING` and `INITIALIZED` when determining a student's final points in an exercise, and reverts a previous change (87dae322fd9777f707db2d0279ccfd1258bf0587), which changed the chapter pages to **not** ignore submissions in those states when determining the students final points.

**Why?**

In a previous commit (87dae322fd9777f707db2d0279ccfd1258bf0587), `UserExerciseSummary` was changed to include submissions in states `WAITING` and `INITIALIZED`, to match the behaviour of the all results table (which uses `CourseResultsDataViewSet`). It was later decided that this should be the other way around: the all results table should ignore submissions in the aforementioned states, like `UserExerciseSummary` and `CachedPoints` did.

**How?**

The `annotate_submitter_points` has been updated to only consider submissions in the state `READY`, unless the `include_unofficial` parameter is `True`, in which case submissions in states `READY` and `UNOFFICIAL` are considered.

The previous change to `UserExerciseSummary` has been reverted.

The `test_annotate_submitter_points` method has also been expanded to cover more situations:
- all submissions are in a state that is not included in the calculation
- `include_unofficial` is `True`
- `revealed_ids` is an empty tuple (no exercises have been revealed)

# Testing

**Remember to add or update unit tests for new features and changes.**

* How to [test your changes in A-plus](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations)
* How to [test accessibility](https://wiki.aalto.fi/display/EDIT/How+to+check+the+accessibility+of+pull+requests)

**What type of test did you run?**

- [ ] Accessibility test using the [WAVE](https://wave.webaim.org/extension/) extension.
- [x] Django unit tests.
- [x] Selenium tests.
- [ ] Other test. *(Add a description below)*
- [x] Manual testing.

Tested manually that submissions in states `WAITING` and `INITIALIZED` are now ignored in the following points calculations:
- user results page (uses `CachedPoints`)
- chapter page (uses `UserExerciseSummary`)
- all results page (uses `CourseResultsDataViewSet`)

**Did you test the changes in**

- [ ] Chrome
- [x] Firefox
- [ ] This pull request cannot be tested in the browser.

**Think of what is affected by these changes and could become broken**

# Translation

- [ ] Did you modify or add new strings in the user interface? ([Read about how to create translation](https://github.com/apluslms/a-plus/tree/master/doc#running-tests-and-updating-translations))

# Programming style

- [x] Did you follow our [style guides](https://apluslms.github.io/contribute/styleguides/)?

# Have you updated the README or other relevant documentation?

- [ ] documents inside the doc directory.
- [ ] README.md.
- [ ] Aplus Manual.
- [ ] Other documentation (mention below which documentation).

# Is it Done?

- [ ] Reviewer has finished the code review
- [ ] After the review, the developer has made changes accordingly
- [ ] Customer/Teacher has accepted the implementation of the feature

*Clean up your git commit history before submitting the pull request!*

2022-01-10 12:38 UTC, skulonen commented on exercise/submission_models.py
> +                ) if not force_zero else models.Value(0),
There was a bug in the previous version: the `if not force_zero else 0` expression applied to the `default` parameter of the `Case`. This means it only applied when the grading mode of the exercise was `BEST` (`default` corresponds to the `BEST` grading mode -- `LAST` and `force_exercise_points` are handled in the other cases). I moved the expression outside of the `Case`, so the entire case expression gets replaced with '0' if none of the exercises have been revealed.

2022-01-10 12:55 UTC, skulonen commented
Regarding the previous PRs related to this issue:
- #944
Can be closed if this is merged, since this PR essentially does the opposite of 944.
- #942
The 404 issue still exists after this PR, because the "best" submission returned by `UserExerciseSummary` and `CachedPoints` may be `None` if every one of a student's submissions is in state `WAITING` or `INITIALIZED`. It was discussed that we could force them to pick one submission as the "best" one, so it would never be `None` as long as there are any non-error submissions. But that would bring about another issue: the "best" submission's points would not necessarily match the exercise's final points returned by `UserExerciseSummary`, `CachedPoints` and `annotate_submitter_points`. Maybe this isn't a real problem, since usually submissions in states `WAITING` and `INITIALIZED` have 0 points?

2022-01-10 13:50 UTC, skulonen commented
More about the best submission / 404 issue:

If we force `UserExerciseSummary` and `CachedPoints` to pick one submission as the "best" one, it would have the following side effects:
- API endpoints that use `ExercisePointsSerializer` would link to the chosen submission in the `best_submission` field, instead of the field being empty.
- The top-left corner of the exercise frame would open the chosen submission, instead of doing nothing.
- The submission list on the Inspect Submission page would place the "Final" marker next to the chosen submission.
- `LTIOutcomeSerializer` would return the chosen submission's score instead of nothing.

2022-01-11 10:04 UTC, Mankro requested changes
Great! Looks good except that one boolean condition in the API view.

2022-01-11 10:16 UTC, skulonen commented on exercise/api/csv/views.py
> +        if show_unofficial:
Yup, that was a bug. Fixed.

2022-01-11 10:37 UTC, Mankro approved these changes

2022-01-11 10:38 UTC, merged